# Generated by Django 4.1.2 on 2022-12-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_district_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='countryid',
            new_name='branchid',
        ),
    ]
