# Generated by Django 4.1.2 on 2022-12-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_countryid_branch_branchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='state',
            new_name='branch',
        ),
    ]
