# Generated by Django 4.1.2 on 2022-12-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='app.register'),
            preserve_default=False,
        ),
    ]
